#!/usr/bin/env fish

not command -aq npx
and echo "Missing 'npx' requirement" >&2
and return 1

not command -aq yarn
and echo "Missing 'yarn' requirement" >&2
and return 1

not command -aq yarn-audit-fix
and echo "Missing 'yarn-audit-fix' requirement" >&2
and return 1

function show_command_and_eval
    echo "$(set_color blue)>_$(set_color --italics green) $argv $(set_color normal)"
    eval $argv 2>/dev/null
end

# packages to skip
set reject_packages \
    web-tree-sitter \
    memfs \
    eslint \
    esbuild \
    vscode-languageserver-protocol \
    $argv

show_command_and_eval npx npm-check-updates --target minor -u --reject (string join -n ',' -- $reject_packages)
and show_command_and_eval yarn install
and show_command_and_eval yarn build
and show_command_and_eval yarn-audit-fix
or {
  echo "$(set_color red)upgrade script stopped...exiting!$(set_color normal)"
  return 1
}
